---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
- name: deployments-routing
- name: routing-release-ci

run:
  path: routing-release-ci/ci/tasks/indicators-test/task

params:
  ENVIRONMENT: batman
